In [1]:
import numpy as np

In [2]:
arr_one = np.array([[1, 2], [3, 4]])
a=arr_one.dtype
b=arr_one.ndim
c=arr_one.shape
print(a)
print(b)
print(c)

int32
2
(2, 2)


In [3]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr2[1:,1:3: ]

array([[ 6,  7],
       [10, 11]])

In [5]:
arr_res = arr2[(arr2>6) & (arr2<10)]

arr_res

array([7, 8, 9])

In [6]:
a=np.array([1,2,3,4],dtype='int32')
a


array([1, 2, 3, 4])

In [7]:
b=np.array([[12,1,2,3,4],[1,2,3,2.0,2.4]])
b

array([[12. ,  1. ,  2. ,  3. ,  4. ],
       [ 1. ,  2. ,  3. ,  2. ,  2.4]])

In [8]:
a.ndim


1

In [9]:
a.shape

(4,)

In [10]:
a.dtype

dtype('int32')

In [11]:
#get size
a.itemsize

4

In [12]:
a.nbytes

16

In [13]:
#to get a specific element
a[1]

2

In [14]:
b[1,1]

2.0

In [15]:
a[0]

1

In [16]:
b[0,0]

12.0

In [17]:
#3,4 matrix with zero
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#3,4matrix with one
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#np.full
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [20]:
np.full_like(a,4)

array([4, 4, 4, 4])

In [21]:
np.random.rand(4,2)
#to have a random matrix

array([[0.29421905, 0.10672795],
       [0.61775781, 0.50162338],
       [0.04499352, 0.9171384 ],
       [0.30618096, 0.8625633 ]])

In [22]:
np.random.randint(4,8, size=(3,3))

array([[5, 7, 7],
       [6, 5, 7],
       [6, 7, 6]])

In [ ]:
arr1=np.array